### ISSUE TITLE
medicine last taken not visible

### ISSUE THREAD

**Issue by vaibhavchellani** [systers/malaria-app-android#163] opened 2017-01-03 09:57 UTC
The medicine last taken field does not show date when the user changes if he has taken the medicine on a particular date through the calendar and comes back to the activity where medicine last taken is shown he sees this 
![image](https://cloud.githubusercontent.com/assets/19390504/21604302/721923f6-d1c8-11e6-9e66-c9b776e10f77.png)

Although when the app is taken out of focus and then in focus again the date appears ,then if we switch activity and come back the date is gone again !
 
can i work on this ?

**Comment by yatna** [comment] 2017-01-03 21:28
Sorry, I did not understand what exactly you were pointing out to. Can you please rephrase your issue.

**Comment by vaibhavchellani** [comment] 2017-01-04 03:00
Yes , when user edits if he has taken a medicine on a selected date  or not through the calendar and navigates back to the activity(posted screenshot above ) the date is not visible .
When the app is taken out of focus and then again into focus the date is visible ,but as soon as we switch activities it again disappears .
I hope i was able to explain the issue correctly . I will post a video showing the issue if its unclear .Thank You

**Comment by yatna** [comment] 2017-01-04 07:49
No, I get what you are trying to say. Actually changing the last medicine through calendar is not updating the home activity as well as the firstActivity fragment. You can go ahead, but first try to find out the root cause of the problem, then we will move to the PR.

**Comment by vaibhavchellani** [comment] 2017-01-04 13:52
yes sure im on it !
thanks

**Comment by anubhakushwaha** [comment] 2017-01-22 05:45
@vaibhavchellani Updates?

**Comment by free4murad** [comment] 2017-01-25 16:14
@anubhakushwaha 
If this issue is free can I work on it??

**Comment by vaibhavchellani** [comment] 2017-01-26 04:59
@free4murad  i`m on it .

**Comment by geekanamika** [comment] 2018-08-13 14:25
not relevant to current UI flow, closing this issue.

**Closed by geekanamika** 2018-08-13 14:25 UTC
