### ISSUE TITLE
White Screen on startup for few seconds.

### ISSUE THREAD

**Issue by harshitagupta30** [systers/malaria-app-android#204] opened 2017-01-13 17:07 UTC
On startup just after installation, a white screen appears for approx 5 seconds and then the main screen appears.
![screenshot_2017-01-13-22-29-03](https://cloud.githubusercontent.com/assets/12701036/21938215/66a6b2c0-d9e0-11e6-8a75-d8d2cded79fc.png)

@yatna and @chhavip please review the issue and let me know.

**Comment by anubhakushwaha** [comment] 2017-01-22 05:51
@harshitagupta30 Before you try to fix it,can you identify the cause behind it and how you are planning to resolve it?

**Comment by harshitagupta30** [comment] 2017-01-22 10:09
@anubhakushwaha That is happening because of the android's cold start. If we are running any type of processing code in our splash screen, all your processing code will run before the screen draws its components in Android so the white screen appears for few seconds. 
But when I checked the app on the other devices it's working absolutely fine. That's an issue with zenfone2. 
So, I guess you can close this issue. :)

**Comment by codingblazer** [comment] 2017-01-22 10:17
@anubhakushwaha Its happening on other devices too. I checked on Moto X style nd Nexus 5. Maybe we can put it on hold until someone find the root cause for this.

**Comment by anubhakushwaha** [comment] 2017-01-25 14:08
In order to avoid hiccups and visually respond as soon as possible to the user interaction, the system displays a temporary window: the “starting window” also known as the “preview window”.There are pretty many ways methods to resolve this,further I hope after resolving #42 we will have less resources to preload . @harshitagupta30 @codingblazer Incase you want to work upon it let us know :)

**Comment by harshitagupta30** [comment] 2017-01-25 14:11
@anubhakushwaha Hi, I am willing to work on this issue :)

**Comment by anubhakushwaha** [comment] 2017-01-25 14:25
Go ahead and let us know the best solution you can implement :+1:

**Comment by top-gun007** [comment] 2017-01-25 17:49
@anubhakushwaha I have a way around for this. Since nearly every app except you-tube shows white screen on its start up. We can implement the same method what you-tube is using.
I am uploading a working solution if you like it then I can send a PR.
![myimage](https://cloud.githubusercontent.com/assets/15179401/22302337/48bbda4c-e354-11e6-9bb1-5c40e07cd125.gif)

**Comment by harshitagupta30** [comment] 2017-01-25 19:49
@anubhakushwaha If we add **<item name="android:windowDisablePreview">true</item> ** in the current theme which is AppTheme in style.xml we can resolve this issue changing the way it looks. I cross checked on 4 devices with different android version and its working absolutely fine. 
Since the initial screen we see known as Preview screen if we disable it we can get desired output.

Can I send the PR for this? :)

**Comment by codingblazer** [comment] 2017-01-26 15:53
@anubhakushwaha The solutions mentioned above are good but they just hides the white screen but not actually reduce startup time. If you say, we can combine these solutions (I can reduce startup time and @harshitagupta30 can add theme) which will be best solution.

**Comment by anubhakushwaha** [comment] 2017-01-26 17:08
@codingblazer How are you planning to reduce the startup time? and @harshitagupta30 please attach a gif of your implemented work.

**Comment by harshitagupta30** [comment] 2017-01-26 17:12
@anubhakushwaha Check this out :)
![videotogif_2017 01 26_22 39 44](https://cloud.githubusercontent.com/assets/12701036/22341905/adaafe32-e418-11e6-8611-fb659d299a24.gif)

**Comment by free4murad** [comment] 2017-01-26 18:13
@harshitagupta30 
I think what you have done is that you have disabled the `preview window`.
If so the drawback is that app will take more time to start. The time for which user has to wait for the  launcher activity to draw on the screen will remain the same.

or If you have used some other approach please tell.

**Comment by harshitagupta30** [comment] 2017-01-26 18:17
@free4murad yeah I have done that thing only. I don't think its increasing any significant amount of time during startup.

**Comment by free4murad** [comment] 2017-01-26 18:20
@harshitagupta30 
I never said it increase the launch time it keeps it the same.

**Comment by harshitagupta30** [comment] 2017-01-26 18:23
@free4murad but in above comment you mentioned that "the drawback is that app will take more time to start" but I couldn't find that happening.

**Comment by free4murad** [comment] 2017-01-26 18:24
@harshitagupta30 
Oh sorry, made a mistake.
My bad.

**Comment by harshitagupta30** [comment] 2017-01-26 18:28
@free4murad No issues. Have you faced this issue while using disabled the preview window?

**Comment by free4murad** [comment] 2017-01-26 18:36
@harshitagupta30 
Actually I was working on some other app sometime back and was facing the same problem.

I think the slow load is because of the complex and big `UserMedicineSettingsFragmentActivity`.

Also `UserMedicineSettingsFragmentActivity` has some memory leak as reported in issue #188 (It might also be responsible for the slow load).

Also if we add a welcome screen in the app (issue #115 ) this will be solved.

**Comment by harshitagupta30** [comment] 2017-01-26 18:43
@free4murad Yeah I also have the same views! :+1: 
@anubhakushwaha Whats your opinion? :)

**Comment by codingblazer** [comment] 2017-01-26 23:13
@anubhakushwaha I will be doing the profiling of the app using adb to measure the actual time for the cold startup. After this i will use the tools like Method tracer and inline tracing to identify the bottlenecks causing this problem and solve them. After this i will look for some common issues like memory leak, heavy initialization in onCreate(), global objects etc

**Comment by anubhakushwaha** [comment] 2017-01-27 06:09
@harshitagupta30 @free4murad @top-gun007 @codingblazer For the time being we can put this on a hold and would proceed with it as per the progress of #115

**Closed by anubhakushwaha** 2017-01-27 06:09 UTC
