### ISSUE TITLE
Generation of sample apk on every merge.

### ISSUE THREAD

**Issue by mahikaw** [systers/malaria-app-android#181] opened 2017-01-08 10:01 UTC
The APK provided in the README file is not updated and could mislead contributors about the progress of the application.
I would like to work on this issue and make this get automatically updated. @chhavip @MeepyMay @yatna please tell me if i can work on this. 😄

**Comment by yatna** [comment] 2017-01-08 12:39
@mahikaw Can you provide a description on how you plan you carry out the auto up-gradation of the .apk if any changes are made in the repo?

**Comment by chhavip** [comment] 2017-01-08 12:54
Also update the issue as it does not concern an errorr in Readme but rather continuous build of the APK file.

**Comment by free4murad** [comment] 2017-01-08 14:25
@yatna @chhavip 
We can integrate travis.
It will check the build and can also be configured to upload successful builds.

If you want I can work on this

**Comment by mahikaw** [comment] 2017-01-08 15:38
@yatna I am using Travis to carry out the auto upgradation. I have already written scripts for this. Just needed the mentor's confirmation before sending a PR.

@free4murad I have already started working on this and have completed this to a good extent so I request you to let me continue.

**Comment by free4murad** [comment] 2017-01-08 15:45
@mahikaw
I just made a suggestion. 
You can continue your work.
Wanted to know if the issue is open.

**Comment by yatna** [comment] 2017-01-10 21:53
@mahikaw You can go ahead.

**Comment by geekanamika** [comment] 2018-08-22 11:15
Resolved in `apk` branch already, closing this issue.

**Closed by geekanamika** 2018-08-22 11:15 UTC
Labels: Priority: HIGH, Status: Available, Type: Maintenance
