### ISSUE TITLE
Bug related to Fragment First Analytic screen

### ISSUE THREAD

**Issue by sridharjajoo** [systers/malaria-app-android#152] opened 2016-12-25 10:08 UTC
When the orientation of the screen is changed then the data of the field Medicine Taken Last Time is lost .For eg. If the last time the medecine was taken was on 25/12 on changing orientation it changes into 25/11
Should I issue a PR?@yatna @chhavip

**Comment by yatna** [comment] 2017-01-03 20:32
@sridharjajoo Yes, first try to find the root cause of the problem. Then you can send a PR.

**Comment by geekanamika** [comment] 2018-08-13 14:27
App is restricted to potrait mode now due to unavailability of landscape layouts. Dialogs works as expect, closing this issue.

**Closed by geekanamika** 2018-08-13 14:27 UTC
