### ISSUE TITLE
App showing Progress bar for future months

### ISSUE THREAD

**Issue by codingblazer** [systers/malaria-app-android#199] opened 2017-01-12 20:27 UTC
**Current** - In Second Analytics Screen, the progress bar for old months - Dec, Nov, Oct opens Calendar for Dec 2017, Nov 2017 etc 
**Expected** - It should open Dec 2016 , Nov 2016 etc.

@chhavip @yatna Should I send PR for this?

**Comment by codingblazer** [comment] 2017-01-22 06:39
@yatna I think this issue has been left. Please review :-)

**Comment by codingblazer** [comment] 2017-01-31 12:29
@yatna @chhavip @anubhakushwaha Can i work on this ?

**Comment by anubhakushwaha** [comment] 2017-01-31 16:34
@codingblazer Could you please report the cause of this bug before implementing it.

**Comment by anubhakushwaha** [comment] 2017-04-21 13:35
@codingblazer Any updates?

**Comment by anubhakushwaha** [comment] 2017-05-03 06:30
@codingblazer Are you working on this?

**Comment by codingblazer** [comment] 2017-05-03 16:36
Really sorry for missing this, i wasn't getting notifications for this project. Yes, I will work on this soon after exams :-)

**Comment by codingblazer** [comment] 2017-05-06 18:24
@anubhakushwaha The reason for the bug is as follows - In ThirdAnalyticFragment.java, year shown is always taken as the current year. This particular case was left out i.e. When current month is Jan/Feb/March then previous months will be from not the current year.

Solution - I will add a **if condition** handling this left out case. @anubhakushwaha Should I send PR for it ?

**Comment by anubhakushwaha** [comment] 2017-05-07 13:48
@codingblazer  Yes go ahead

**Comment by geekanamika** [comment] 2018-08-13 14:33
Issue is handled in PR #370 
Closing this issue.

**Closed by geekanamika** 2018-08-13 14:33 UTC
