### ISSUE TITLE
Bug in achivementRoom share message.

### ISSUE THREAD

**Issue by free4murad** [systers/malaria-app-android#185] opened 2017-01-08 14:53 UTC
In Achievement Room user can share his/her progress.
But the name of the user in the message is Yatna.
We should make change this by making a general message like "Hey, I unlocked a new badge......."

@yatna @chhavip 
Is this a bug or is it intended this way.
Also should I make a PR.

**Comment by yatna** [comment] 2017-01-12 21:26
@free4murad No, that is not a bug. Actually, it is intended to get the registered name from the app. But currently since, registration is still in development phase, for the time the message is temporarily like this.
You can close this issue.

**Closed** 2017-01-13 05:03 UTC

**Comment by anubhakushwaha** [comment] 2017-04-21 13:39
@may Are we including registration now?
